var
  _CONTROLS : Array[0..11] of Pointer absolute CONTROLS_ADDR;
  _ICONS    : Array[0.. 8] of Pointer absolute ICONS_ADDR;
  _ICARD    : Pointer                 absolute ICARD_ADDR;
  _IPATH    : Pointer                 absolute IPATH_ADDR;
  _VSCROLL  : Pointer                 absolute VSCROLL_ADDR;
  _ARROW    : Pointer                 absolute CARROW_ADDR;
  _WAIT     : Pointer                 absolute CWAIT_ADDR;